"""initial_schema

Revision ID: 531105830bf3
Revises: 
Create Date: 2026-04-13 20:46:46.253407

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '531105830bf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('account_status', sa.Enum('PENDING', 'VERIFIED', 'SUSPENDED', name='userstatusenum'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_pic', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_table('weddings',
    sa.Column('groom_name', sa.String(length=255), nullable=False),
    sa.Column('bride_name', sa.String(length=255), nullable=False),
    sa.Column('groom_name_short', sa.String(length=100), nullable=True),
    sa.Column('bride_name_short', sa.String(length=100), nullable=True),
    sa.Column('wedding_date', sa.Date(), nullable=True),
    sa.Column('venue_name', sa.String(length=500), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('venue_lat', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('venue_lng', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('theme', sa.Enum('GARDEN', 'RUSTIC', 'MODERN', 'TRADITIONAL', 'BEACH', 'ROYAL', 'MINIMALIST', 'OTHER', name='weddingthemeenum'), nullable=True),
    sa.Column('budget_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cover_photo', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weddings_id'), 'weddings', ['id'], unique=False)
    op.create_index(op.f('ix_weddings_status'), 'weddings', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('wedding_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_wedding_id'), 'audit_logs', ['wedding_id'], unique=False)
    op.create_table('budget_items',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('CATERING', 'PELAMIN', 'PHOTOGRAPHY', 'VIDEOGRAPHY', 'MAKEUP', 'ATTIRE', 'DECORATION', 'INVITATION', 'ENTERTAINMENT', 'TRANSPORTATION', 'VENUE', 'HONEYMOON', 'MISCELLANEOUS', name='budgetcategoryenum'), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('estimated_amount_encrypted', sa.Text(), nullable=True),
    sa.Column('actual_amount_encrypted', sa.Text(), nullable=True),
    sa.Column('paid_amount_encrypted', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_items_category'), 'budget_items', ['category'], unique=False)
    op.create_index(op.f('ix_budget_items_id'), 'budget_items', ['id'], unique=False)
    op.create_index(op.f('ix_budget_items_status'), 'budget_items', ['status'], unique=False)
    op.create_index(op.f('ix_budget_items_wedding_id'), 'budget_items', ['wedding_id'], unique=False)
    op.create_table('event_schedules',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('ENGAGEMENT', 'REHEARSAL', 'WEDDING_DAY', 'POST_WEDDING', 'OTHER', name='scheduletypeenum'), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsible_person', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_schedules_event_type'), 'event_schedules', ['event_type'], unique=False)
    op.create_index(op.f('ix_event_schedules_id'), 'event_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_event_schedules_status'), 'event_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_event_schedules_wedding_id'), 'event_schedules', ['wedding_id'], unique=False)
    op.create_table('honeymoons',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('budget_total_encrypted', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honeymoons_id'), 'honeymoons', ['id'], unique=False)
    op.create_index(op.f('ix_honeymoons_status'), 'honeymoons', ['status'], unique=False)
    op.create_index(op.f('ix_honeymoons_wedding_id'), 'honeymoons', ['wedding_id'], unique=True)
    op.create_table('invitations',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.UUID(), nullable=False),
    sa.Column('theme', sa.Enum('CLASSIC', 'MODERN', 'FLORAL', 'MINIMALIST', 'ROYAL', name='invitationthemeenum'), nullable=False),
    sa.Column('language', sa.Enum('MS', 'EN', 'DUAL', name='languageenum'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('show_love_story', sa.Boolean(), nullable=False),
    sa.Column('show_meal_preference', sa.Boolean(), nullable=False),
    sa.Column('show_gift_registry', sa.Boolean(), nullable=False),
    sa.Column('show_dress_code', sa.Boolean(), nullable=False),
    sa.Column('enable_rsvp', sa.Boolean(), nullable=False),
    sa.Column('rsvp_max_pax', sa.Integer(), nullable=True),
    sa.Column('enable_countdown', sa.Boolean(), nullable=False),
    sa.Column('enable_music', sa.Boolean(), nullable=False),
    sa.Column('music_url', sa.String(length=500), nullable=True),
    sa.Column('dress_code_description', sa.Text(), nullable=True),
    sa.Column('dress_code_colors', sa.Text(), nullable=True),
    sa.Column('gift_registry_url', sa.String(length=500), nullable=True),
    sa.Column('duitnow_qr_url', sa.String(length=500), nullable=True),
    sa.Column('custom_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_id'), 'invitations', ['id'], unique=False)
    op.create_index(op.f('ix_invitations_slug'), 'invitations', ['slug'], unique=True)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    op.create_index(op.f('ix_invitations_wedding_id'), 'invitations', ['wedding_id'], unique=True)
    op.create_table('menu_items',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('MAIN_COURSE', 'SIDE_DISH', 'DESSERT', 'BEVERAGE', 'APPETIZER', 'OTHER', name='menucategoryenum'), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('is_vegetarian', sa.Boolean(), nullable=False),
    sa.Column('is_halal', sa.Boolean(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_category'), 'menu_items', ['category'], unique=False)
    op.create_index(op.f('ix_menu_items_id'), 'menu_items', ['id'], unique=False)
    op.create_index(op.f('ix_menu_items_status'), 'menu_items', ['status'], unique=False)
    op.create_index(op.f('ix_menu_items_wedding_id'), 'menu_items', ['wedding_id'], unique=False)
    op.create_table('moodboards',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('COLORS', 'DECOR', 'FLOWERS', 'OUTFIT', 'VENUE', 'FOOD', 'INVITATION', 'HAIR_MAKEUP', 'OTHER', name='moodboardcategoryenum'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodboards_category'), 'moodboards', ['category'], unique=False)
    op.create_index(op.f('ix_moodboards_id'), 'moodboards', ['id'], unique=False)
    op.create_index(op.f('ix_moodboards_status'), 'moodboards', ['status'], unique=False)
    op.create_index(op.f('ix_moodboards_wedding_id'), 'moodboards', ['wedding_id'], unique=False)
    op.create_table('otp_verifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_verifications_id'), 'otp_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_otp_verifications_status'), 'otp_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False)
    op.create_table('seating_tables',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('table_number', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seating_tables_id'), 'seating_tables', ['id'], unique=False)
    op.create_index(op.f('ix_seating_tables_status'), 'seating_tables', ['status'], unique=False)
    op.create_index(op.f('ix_seating_tables_wedding_id'), 'seating_tables', ['wedding_id'], unique=False)
    op.create_table('tasks',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('phase', sa.Enum('PHASE_1_RESEARCH', 'PHASE_2_BOOKING', 'PHASE_3_PREPARATION', 'PHASE_4_FINAL', 'BIG_DAY', 'POST_WEDDING', name='taskphaseenum'), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_is_completed'), 'tasks', ['is_completed'], unique=False)
    op.create_index(op.f('ix_tasks_phase'), 'tasks', ['phase'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_wedding_id'), 'tasks', ['wedding_id'], unique=False)
    op.create_table('vendors',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('CATERING', 'PELAMIN', 'PHOTOGRAPHY', 'VIDEOGRAPHY', 'MAKEUP', 'ATTIRE', 'DECORATION', 'ENTERTAINMENT', 'TRANSPORTATION', 'VENUE', 'CAKE', 'FLORIST', 'OTHER', name='vendorcategoryenum'), nullable=False),
    sa.Column('vendor_status', sa.Enum('PROSPECT', 'CONTACTED', 'BOOKED', 'DEPOSIT_PAID', 'FULLY_PAID', 'COMPLETED', 'CANCELLED', name='vendorstatusenum'), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('instagram', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('price_encrypted', sa.Text(), nullable=True),
    sa.Column('deposit_paid_encrypted', sa.Text(), nullable=True),
    sa.Column('balance_due_encrypted', sa.Text(), nullable=True),
    sa.Column('payment_due_date', sa.Date(), nullable=True),
    sa.Column('contract_signed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_category'), 'vendors', ['category'], unique=False)
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_status'), 'vendors', ['status'], unique=False)
    op.create_index(op.f('ix_vendors_wedding_id'), 'vendors', ['wedding_id'], unique=False)
    op.create_table('wedding_collaborators',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('GROOM', 'BRIDE', 'ADMIN', 'VIEWER', name='collaboratorroleenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wedding_collaborators_id'), 'wedding_collaborators', ['id'], unique=False)
    op.create_index(op.f('ix_wedding_collaborators_status'), 'wedding_collaborators', ['status'], unique=False)
    op.create_index(op.f('ix_wedding_collaborators_user_id'), 'wedding_collaborators', ['user_id'], unique=False)
    op.create_index(op.f('ix_wedding_collaborators_wedding_id'), 'wedding_collaborators', ['wedding_id'], unique=False)
    op.create_table('contact_persons',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_persons_id'), 'contact_persons', ['id'], unique=False)
    op.create_index(op.f('ix_contact_persons_invitation_id'), 'contact_persons', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_contact_persons_status'), 'contact_persons', ['status'], unique=False)
    op.create_table('gallery_photos',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_photos_id'), 'gallery_photos', ['id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_invitation_id'), 'gallery_photos', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_gallery_photos_status'), 'gallery_photos', ['status'], unique=False)
    op.create_table('guestbook_entries',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guestbook_entries_id'), 'guestbook_entries', ['id'], unique=False)
    op.create_index(op.f('ix_guestbook_entries_invitation_id'), 'guestbook_entries', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_guestbook_entries_status'), 'guestbook_entries', ['status'], unique=False)
    op.create_table('guests',
    sa.Column('wedding_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('side', sa.Enum('GROOM', 'BRIDE', 'BOTH', name='guestsideenum'), nullable=False),
    sa.Column('rsvp_status', sa.Enum('PENDING', 'ATTENDING', 'NOT_ATTENDING', 'MAYBE', name='rsvpstatusenum'), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('table_id', sa.UUID(), nullable=True),
    sa.Column('meal_preference', sa.Enum('NORMAL', 'VEGETARIAN', 'VEGAN', 'HALAL', 'OTHER', name='mealpreferenceenum'), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['table_id'], ['seating_tables.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wedding_id'], ['weddings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guests_id'), 'guests', ['id'], unique=False)
    op.create_index(op.f('ix_guests_rsvp_status'), 'guests', ['rsvp_status'], unique=False)
    op.create_index(op.f('ix_guests_status'), 'guests', ['status'], unique=False)
    op.create_index(op.f('ix_guests_wedding_id'), 'guests', ['wedding_id'], unique=False)
    op.create_table('honeymoon_items',
    sa.Column('honeymoon_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('FLIGHT', 'HOTEL', 'ACTIVITIES', 'FOOD', 'SHOPPING', 'TRANSPORT', 'INSURANCE', 'OTHER', name='honeymoonitemcategoryenum'), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('booking_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost_encrypted', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['honeymoon_id'], ['honeymoons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_honeymoon_items_category'), 'honeymoon_items', ['category'], unique=False)
    op.create_index(op.f('ix_honeymoon_items_honeymoon_id'), 'honeymoon_items', ['honeymoon_id'], unique=False)
    op.create_index(op.f('ix_honeymoon_items_id'), 'honeymoon_items', ['id'], unique=False)
    op.create_index(op.f('ix_honeymoon_items_status'), 'honeymoon_items', ['status'], unique=False)
    op.create_table('love_stories',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_love_stories_id'), 'love_stories', ['id'], unique=False)
    op.create_index(op.f('ix_love_stories_invitation_id'), 'love_stories', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_love_stories_status'), 'love_stories', ['status'], unique=False)
    op.create_table('rsvp_responses',
    sa.Column('invitation_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('response', sa.Enum('ATTENDING', 'NOT_ATTENDING', 'MAYBE', name='rsvpresponseenum'), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('meal_preference', sa.String(length=50), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invitation_id'], ['invitations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rsvp_responses_id'), 'rsvp_responses', ['id'], unique=False)
    op.create_index(op.f('ix_rsvp_responses_invitation_id'), 'rsvp_responses', ['invitation_id'], unique=False)
    op.create_index(op.f('ix_rsvp_responses_status'), 'rsvp_responses', ['status'], unique=False)
    op.create_table('vendor_documents',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('document_type', sa.Enum('CONTRACT', 'INVOICE', 'RECEIPT', 'OTHER', name='documenttypeenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_documents_id'), 'vendor_documents', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_documents_status'), 'vendor_documents', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_documents_vendor_id'), 'vendor_documents', ['vendor_id'], unique=False)
    op.create_table('vendor_reviews',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('would_recommend', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_reviews_id'), 'vendor_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_vendor_reviews_status'), 'vendor_reviews', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_reviews_vendor_id'), 'vendor_reviews', ['vendor_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendor_reviews_vendor_id'), table_name='vendor_reviews')
    op.drop_index(op.f('ix_vendor_reviews_status'), table_name='vendor_reviews')
    op.drop_index(op.f('ix_vendor_reviews_id'), table_name='vendor_reviews')
    op.drop_table('vendor_reviews')
    op.drop_index(op.f('ix_vendor_documents_vendor_id'), table_name='vendor_documents')
    op.drop_index(op.f('ix_vendor_documents_status'), table_name='vendor_documents')
    op.drop_index(op.f('ix_vendor_documents_id'), table_name='vendor_documents')
    op.drop_table('vendor_documents')
    op.drop_index(op.f('ix_rsvp_responses_status'), table_name='rsvp_responses')
    op.drop_index(op.f('ix_rsvp_responses_invitation_id'), table_name='rsvp_responses')
    op.drop_index(op.f('ix_rsvp_responses_id'), table_name='rsvp_responses')
    op.drop_table('rsvp_responses')
    op.drop_index(op.f('ix_love_stories_status'), table_name='love_stories')
    op.drop_index(op.f('ix_love_stories_invitation_id'), table_name='love_stories')
    op.drop_index(op.f('ix_love_stories_id'), table_name='love_stories')
    op.drop_table('love_stories')
    op.drop_index(op.f('ix_honeymoon_items_status'), table_name='honeymoon_items')
    op.drop_index(op.f('ix_honeymoon_items_id'), table_name='honeymoon_items')
    op.drop_index(op.f('ix_honeymoon_items_honeymoon_id'), table_name='honeymoon_items')
    op.drop_index(op.f('ix_honeymoon_items_category'), table_name='honeymoon_items')
    op.drop_table('honeymoon_items')
    op.drop_index(op.f('ix_guests_wedding_id'), table_name='guests')
    op.drop_index(op.f('ix_guests_status'), table_name='guests')
    op.drop_index(op.f('ix_guests_rsvp_status'), table_name='guests')
    op.drop_index(op.f('ix_guests_id'), table_name='guests')
    op.drop_table('guests')
    op.drop_index(op.f('ix_guestbook_entries_status'), table_name='guestbook_entries')
    op.drop_index(op.f('ix_guestbook_entries_invitation_id'), table_name='guestbook_entries')
    op.drop_index(op.f('ix_guestbook_entries_id'), table_name='guestbook_entries')
    op.drop_table('guestbook_entries')
    op.drop_index(op.f('ix_gallery_photos_status'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_invitation_id'), table_name='gallery_photos')
    op.drop_index(op.f('ix_gallery_photos_id'), table_name='gallery_photos')
    op.drop_table('gallery_photos')
    op.drop_index(op.f('ix_contact_persons_status'), table_name='contact_persons')
    op.drop_index(op.f('ix_contact_persons_invitation_id'), table_name='contact_persons')
    op.drop_index(op.f('ix_contact_persons_id'), table_name='contact_persons')
    op.drop_table('contact_persons')
    op.drop_index(op.f('ix_wedding_collaborators_wedding_id'), table_name='wedding_collaborators')
    op.drop_index(op.f('ix_wedding_collaborators_user_id'), table_name='wedding_collaborators')
    op.drop_index(op.f('ix_wedding_collaborators_status'), table_name='wedding_collaborators')
    op.drop_index(op.f('ix_wedding_collaborators_id'), table_name='wedding_collaborators')
    op.drop_table('wedding_collaborators')
    op.drop_index(op.f('ix_vendors_wedding_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_status'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_index(op.f('ix_vendors_category'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_tasks_wedding_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_phase'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_is_completed'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_seating_tables_wedding_id'), table_name='seating_tables')
    op.drop_index(op.f('ix_seating_tables_status'), table_name='seating_tables')
    op.drop_index(op.f('ix_seating_tables_id'), table_name='seating_tables')
    op.drop_table('seating_tables')
    op.drop_index(op.f('ix_otp_verifications_user_id'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_status'), table_name='otp_verifications')
    op.drop_index(op.f('ix_otp_verifications_id'), table_name='otp_verifications')
    op.drop_table('otp_verifications')
    op.drop_index(op.f('ix_moodboards_wedding_id'), table_name='moodboards')
    op.drop_index(op.f('ix_moodboards_status'), table_name='moodboards')
    op.drop_index(op.f('ix_moodboards_id'), table_name='moodboards')
    op.drop_index(op.f('ix_moodboards_category'), table_name='moodboards')
    op.drop_table('moodboards')
    op.drop_index(op.f('ix_menu_items_wedding_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_status'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_id'), table_name='menu_items')
    op.drop_index(op.f('ix_menu_items_category'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_invitations_wedding_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_slug'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_id'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_honeymoons_wedding_id'), table_name='honeymoons')
    op.drop_index(op.f('ix_honeymoons_status'), table_name='honeymoons')
    op.drop_index(op.f('ix_honeymoons_id'), table_name='honeymoons')
    op.drop_table('honeymoons')
    op.drop_index(op.f('ix_event_schedules_wedding_id'), table_name='event_schedules')
    op.drop_index(op.f('ix_event_schedules_status'), table_name='event_schedules')
    op.drop_index(op.f('ix_event_schedules_id'), table_name='event_schedules')
    op.drop_index(op.f('ix_event_schedules_event_type'), table_name='event_schedules')
    op.drop_table('event_schedules')
    op.drop_index(op.f('ix_budget_items_wedding_id'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_status'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_id'), table_name='budget_items')
    op.drop_index(op.f('ix_budget_items_category'), table_name='budget_items')
    op.drop_table('budget_items')
    op.drop_index(op.f('ix_audit_logs_wedding_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_weddings_status'), table_name='weddings')
    op.drop_index(op.f('ix_weddings_id'), table_name='weddings')
    op.drop_table('weddings')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
